name: idk

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Update timestamp file
        run: |
            git config user.name "Pang YS"
            git config user.email "devbx@proton.me"
            echo "Last updated: $(TZ='Asia/Kuching' date)" > timestamp.txt
            git add timestamp.txt
            git commit -m "Update timestamp: $(TZ='Asia/Kuching' date)" || exit 0
            git push origin master