name: idk

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Commit and push if it is changed
        run: |
          git config user.name "Pang YS"
          git config user.email "devbx@proton.me"
          git add -A
          timestamp=$(TZ="Asia/Kuching" date)
          git commit -m "Last Commit: ${timestamp}(TW)" || exit 0
          git push origin master
